const products=[{id:1,name:'Pan Francés',price:1500,img:'assets/panes.jpg'},{id:2,name:'Croissant',price:3800,img:'assets/croissant.jpg'},{id:3,name:'Torta de Chocolate',price:6200,img:'assets/torta.jpg'},{id:4,name:'Café Latte',price:4500,img:'assets/cafe_latte.jpg'},{id:5,name:'Café Americano',price:4000,img:'assets/cafe_americano.jpg'}];
const money=n=>`$${Number(n).toFixed(2)}`;
const getCart=()=>JSON.parse(localStorage.getItem('calicheCart')||'[]');
const saveCart=cart=>localStorage.setItem('calicheCart',JSON.stringify(cart));
function addToCart(id){let cart=getCart();let item=cart.find(p=>p.id===id);item?item.qty++:cart.push({...products.find(p=>p.id===id),qty:1});saveCart(cart);alert('Producto agregado al carrito');}
function changeQty(id,delta){let cart=getCart().map(p=>p.id===id?{...p,qty:p.qty+delta}:p).filter(p=>p.qty>0);saveCart(cart);renderCart();}
function removeItem(id){saveCart(getCart().filter(p=>p.id!==id));renderCart();}
function renderProducts(list=products){const grid=document.getElementById('productGrid');if(!grid)return;grid.innerHTML=list.map(p=>`<article class="product"><img src="${p.img}" alt="${p.name}"><h3>${p.name}</h3><div class="product__foot"><span class="price">${money(p.price)}</span><button class="round" onclick="addToCart(${p.id})">+</button></div></article>`).join('');}
function filterProducts(){const term=document.getElementById('searchInput').value.toLowerCase();renderProducts(products.filter(p=>p.name.toLowerCase().includes(term)));}
function renderCart(){const wrap=document.getElementById('cartItems');if(!wrap)return;const cart=getCart();document.getElementById('cartCount').textContent=`${cart.length} productos`;wrap.innerHTML=cart.length?cart.map(p=>`<article class="cart-item"><img src="${p.img}" alt="${p.name}"><div><h3>${p.name}</h3><span class="price">${money(p.price)}</span><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${p.qty}</span><button onclick="changeQty(${p.id},1)">+</button></div></div><div><button class="trash" onclick="removeItem(${p.id})">🗑️</button><strong>${money(p.price*p.qty)}</strong></div></article>`).join(''):'<p class="muted">Tu carrito está vacío.</p>';let total=cart.reduce((s,p)=>s+p.price*p.qty,0);document.getElementById('subtotal').textContent=money(total);document.getElementById('total').textContent=money(total);}
function loginUser(e){e.preventDefault();localStorage.setItem('calicheUser',JSON.stringify({name:'Juan Pérez',email:document.getElementById('loginEmail').value,phone:'+56 9 1234 5678'}));location.href='catalogo.html';}
function registerUser(e){e.preventDefault();localStorage.setItem('calicheUser',JSON.stringify({name:regName.value,email:regEmail.value,phone:regPhone.value}));location.href='catalogo.html';}
function loadProfile(){const u=JSON.parse(localStorage.getItem('calicheUser')||'{"name":"Juan Pérez","email":"juan.perez@email.com","phone":"+56 9 1234 5678"}');['profileName','infoName'].forEach(id=>{let el=document.getElementById(id);if(el)el.textContent=u.name});['profileEmail','infoEmail'].forEach(id=>{let el=document.getElementById(id);if(el)el.textContent=u.email});let phone=document.getElementById('infoPhone');if(phone)phone.textContent=u.phone;}
function checkout(){alert('Pedido registrado. Gracias por comprar en Caliche Pan.');localStorage.removeItem('calicheCart');renderCart();}
document.addEventListener('DOMContentLoaded',()=>{renderProducts();renderCart();loadProfile();});
